<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
@php
    app()->setLocale($language);
@endphp
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{{ $subject }}</title>
</head>
<body>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        tr:nth-child(even) {
            background-color: #dddddd;
        }
        .header {
            font-weight: bold;
            margin-bottom: 20px;
        }
        .summary {
            margin: 20px 0;
            padding: 15px;
            background-color: #f5f5f5;
        }
        .report-section {
            margin: 20px 0;
        }
    </style>
    
    <!-- Email Header -->
    <div class="header">
        <h2>{{ __('Renewal Report') }}</h2>
        <p>{{ __('Generated on') }}: {{ $generated_at->format('d/m/Y H:i') }}</p>
        <p>{{ __('Recipient') }}: {{ $recipient }}</p>
    </div>
    
    <!-- Summary -->
    <div class="summary">
        <h3>{{ __('Report Summary') }}</h3>
        <p><strong>{{ __('Total Renewals') }}:</strong> {{ $total_count }}</p>
        <p><strong>{{ __('Total Official Fees') }}:</strong> {{ number_format($total_cost, 2) }} €</p>
        <p><strong>{{ __('Total Service Fees') }}:</strong> {{ number_format($total_fee, 2) }} €</p>
        <p><strong>{{ __('Grand Total') }}:</strong> {{ number_format($total_cost + $total_fee, 2) }} €</p>
    </div>

    <!-- Renewals Details -->
    <div class="report-section">
        <h3>{{ __('Renewal Details') }}</h3>
        <table class="inner-body" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>{{ __('Case Reference') }}</th>
                    <th>{{ __('Client') }}</th>
                    <th>{{ __('Country') }}</th>
                    <th>{{ __('Due Date') }}</th>
                    <th>{{ __('Status') }}</th>
                    <th>{{ __('Official Fee') }}</th>
                    <th>{{ __('Service Fee') }}</th>
                    <th>{{ __('Total') }} (€)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($renewals as $renewal)
                <tr>
                    <td>{{ $renewal->caseref ?? 'N/A' }}</td>
                    <td>{{ $renewal->clientName ?? 'N/A' }}</td>
                    <td style="text-align: center;">{{ $renewal->country ?? 'N/A' }}</td>
                    <td style="text-align: center;">
                        @if($renewal->due_date)
                            {{ \Carbon\Carbon::parse($renewal->due_date)->format('d/m/Y') }}
                        @else
                            N/A
                        @endif
                    </td>
                    <td style="text-align: center;">
                        @switch($renewal->step ?? 0)
                            @case(1)
                                {{ __('First Call') }}
                                @break
                            @case(2)
                                {{ __('Warning') }}
                                @break
                            @case(3)
                                {{ __('Last Call') }}
                                @break
                            @case(4)
                                {{ __('Invoice Sent') }}
                                @break
                            @default
                                {{ __('Pending') }}
                        @endswitch
                    </td>
                    <td style="text-align: right;">{{ number_format($renewal->cost ?? 0, 2) }}</td>
                    <td style="text-align: right;">{{ number_format($renewal->fee ?? 0, 2) }}</td>
                    <td style="text-align: right;">{{ number_format(($renewal->cost ?? 0) + ($renewal->fee ?? 0), 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Additional Notes -->
    <div class="report-section">
        <h3>{{ __('Notes') }}</h3>
        <p>{{ __('This report was automatically generated by the renewal system.') }}</p>
        <p>{{ __('For any questions regarding this report, please contact the renewal team.') }}</p>
    </div>

    <!-- Footer -->
    <p>{{ __('Best regards') }},</p>
    <p>{{ Auth::user()->name ?? config('app.name') }}</p>
</body>
</html>